name: DDTV_WEB_Server

on:
  push:
    branches: [ master ]
    paths:
      - 'DDTV_WEB_Server/**'
      - '.github/workflows/DDTV_WEB_Server.yml'
      - '!**/README.md'
  pull_request:
    branches: [ master ]
    paths:
      - 'DDTV_WEB_Server/**'
      - '.github/workflows/DDTV_WEB_Server.yml'
      - '!**/README.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: cd DDTV_WEB_Server && dotnet restore
    - name: Build
      run: cd DDTV_WEB_Server && dotnet build --no-restore
